### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by Akatsuki2555** [Akatsuki2555/Akabot#31]
https://github.com/Akatsuki2555/Akabot/blob/d522c90b0e1ca4bf56c4c0fc34c9a75b4bc012e7/features/logging_mod.py#L138

```
bot_1  | Traceback (most recent call last):
bot_1  |   File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 400, in _run_event
bot_1  |     await coro(*args, **kwargs)
bot_1  |   File "/app/features/logging_mod.py", line 138, in on_guild_channel_update
bot_1  |     if len(before_topic) == 0:
bot_1  |        ^^^^^^^^^^^^^^^^^
bot_1  | TypeError: object of type 'NoneType' has no len()
```

**Comment by Akatsuki2555** [comment]
Fixed
