### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by Akatsuki2555** [Akatsuki2555/Akabot#32]
https://github.com/Akatsuki2555/Akabot/blob/fe9e975786999be7e389c98bea478f5ca7bbee79/features/logging_mod.py#L143

```
bot_1  | Traceback (most recent call last):
bot_1  |   File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 400, in _run_event
bot_1  |     await coro(*args, **kwargs)
bot_1  |   File "/app/features/logging_mod.py", line 143, in on_guild_channel_update
bot_1  |     if len(after_topic) == 0:
bot_1  |        ^^^^^^^^^^^^^^^^
bot_1  | TypeError: object of type 'NoneType' has no len()
```

**Comment by Akatsuki2555** [comment]
Fixed
