### ISSUE TITLE
TypeError: 'Permissions' object is not subscriptable

### ISSUE THREAD

**Issue by Akatsuki2555** [Akatsuki2555/Akabot#33]
https://github.com/Akatsuki2555/Akabot/blob/fe9e975786999be7e389c98bea478f5ca7bbee79/features/logging_mod.py#L243

```
bot_1  | Traceback (most recent call last):
bot_1  |   File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 400, in _run_event
bot_1  |     await coro(*args, **kwargs)
bot_1  |   File "/app/features/logging_mod.py", line 243, in on_guild_role_update
bot_1  |     if before.permissions[perm] == after.permissions[perm]:
bot_1  |        ~~~~~~~~~~~~~~~~~~^^^^^^
bot_1  | TypeError: 'Permissions' object is not subscriptable
```

**Comment by Akatsuki2555** [comment]
Fixed
